In [1]:
import numpy as np
import pandas as pd

In [3]:
features = pd.read_csv('/home/dongsu/Downloads/temps.csv')
features.head(5)

year  month  day  week  temp_2  temp_1  average  actual  forecast_noaa  \
0  2016      1    1   Fri      45      45     45.6      45             43   
1  2016      1    2   Sat      44      45     45.7      44             41   
2  2016      1    3   Sun      45      44     45.8      41             43   
3  2016      1    4   Mon      44      41     45.9      40             44   
4  2016      1    5  Tues      41      40     46.0      44             46   

   forecast_acc  forecast_under  friend  
0            50              44      29  
1            50              44      61  
2            46              47      56  
3            48              46      53  
4            46              46      41

In [9]:
new_df = features[['year','month','day','week','temp_2','temp_1','average',
         'actual','friend']]

In [10]:
new_df.head(5)

year  month  day  week  temp_2  temp_1  average  actual  friend
0  2016      1    1   Fri      45      45     45.6      45      29
1  2016      1    2   Sat      44      45     45.7      44      61
2  2016      1    3   Sun      45      44     45.8      41      56
3  2016      1    4   Mon      44      41     45.9      40      53
4  2016      1    5  Tues      41      40     46.0      44      41

In [11]:
new_df.shape

(348, 9)

In [12]:
new_df.describe()

year       month         day      temp_2      temp_1     average  \
count   348.0  348.000000  348.000000  348.000000  348.000000  348.000000   
mean   2016.0    6.477011   15.514368   62.652299   62.701149   59.760632   
std       0.0    3.498380    8.772982   12.165398   12.120542   10.527306   
min    2016.0    1.000000    1.000000   35.000000   35.000000   45.100000   
25%    2016.0    3.000000    8.000000   54.000000   54.000000   49.975000   
50%    2016.0    6.000000   15.000000   62.500000   62.500000   58.200000   
75%    2016.0   10.000000   23.000000   71.000000   71.000000   69.025000   
max    2016.0   12.000000   31.000000  117.000000  117.000000   77.400000   

           actual      friend  
count  348.000000  348.000000  
mean    62.543103   60.034483  
std     11.794146   15.626179  
min     35.000000   28.000000  
25%     54.000000   47.750000  
50%     62.500000   60.000000  
75%     71.000000   71.000000  
max     92.000000   95.000000

In [21]:
features = pd.get_dummies(new_df)

In [22]:
# Labels are the values we want to predict
labels = np.array(features['actual'])
# Remove the labels from the features
# axis 1 refers to the columns
features= features.drop('actual', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
features = np.array(features)

In [26]:
features

array([[  2.01600000e+03,   1.00000000e+00,   1.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  2.01600000e+03,   1.00000000e+00,   2.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  2.01600000e+03,   1.00000000e+00,   3.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       ..., 
       [  2.01600000e+03,   1.20000000e+01,   2.90000000e+01, ...,
          1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  2.01600000e+03,   1.20000000e+01,   3.00000000e+01, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  2.01600000e+03,   1.20000000e+01,   3.10000000e+01, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

In [28]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [31]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (261, 14)
Training Labels Shape: (261,)
Testing Features Shape: (87, 14)
Testing Labels Shape: (87,)


In [32]:
baseline_preds = test_features[:, feature_list.index('average')]
baseline_preds

array([ 66.1,  60.7,  48. ,  61. ,  70.4,  63. ,  77.1,  76.6,  55.6,
        68. ,  54.2,  68.3,  45.9,  59.9,  71.5,  49.4,  52.2,  54.5,
        51.3,  72.4,  63.3,  50. ,  69.7,  59.9,  55.2,  48.3,  66.1,
        46.5,  65.9,  76. ,  59.7,  61.2,  48. ,  76.5,  77.4,  51.2,
        49.6,  48.7,  73.5,  45.1,  61.6,  55.5,  59.4,  46.1,  57.8,
        61.9,  51.5,  76.8,  53.9,  46.4,  45.1,  45.9,  64.9,  66.8,
        72.1,  56.5,  50.1,  54.5,  53.7,  60.5,  68.8,  48.9,  52.4,
        70. ,  54.3,  56.8,  73.3,  74. ,  76.6,  46. ,  72.6,  54.6,
        56.3,  47.4,  52.8,  63.4,  46.3,  76.9,  45.3,  49.1,  50. ,
        56.9,  67.9,  70. ,  63.7,  51.9,  45.1])

In [34]:
test_labels

array([66, 61, 52, 66, 70, 82, 85, 84, 65, 92, 61, 85, 44, 65, 69, 62, 64,
       56, 53, 79, 63, 57, 67, 62, 59, 56, 65, 52, 66, 76, 64, 61, 48, 81,
       77, 57, 58, 47, 68, 51, 77, 56, 73, 51, 59, 87, 58, 81, 58, 42, 49,
       40, 65, 64, 70, 65, 53, 57, 53, 60, 67, 49, 53, 69, 55, 68, 76, 69,
       78, 36, 74, 57, 69, 50, 56, 67, 48, 80, 48, 49, 57, 77, 81, 67, 66,
       57, 45])

In [36]:
abs(baseline_preds - test_labels)

array([  0.1,   0.3,   4. ,   5. ,   0.4,  19. ,   7.9,   7.4,   9.4,
        24. ,   6.8,  16.7,   1.9,   5.1,   2.5,  12.6,  11.8,   1.5,
         1.7,   6.6,   0.3,   7. ,   2.7,   2.1,   3.8,   7.7,   1.1,
         5.5,   0.1,   0. ,   4.3,   0.2,   0. ,   4.5,   0.4,   5.8,
         8.4,   1.7,   5.5,   5.9,  15.4,   0.5,  13.6,   4.9,   1.2,
        25.1,   6.5,   4.2,   4.1,   4.4,   3.9,   5.9,   0.1,   2.8,
         2.1,   8.5,   2.9,   2.5,   0.7,   0.5,   1.8,   0.1,   0.6,
         1. ,   0.7,  11.2,   2.7,   5. ,   1.4,  10. ,   1.4,   2.4,
        12.7,   2.6,   3.2,   3.6,   1.7,   3.1,   2.7,   0.1,   7. ,
        20.1,  13.1,   3. ,   2.3,   5.1,   0.1])

In [37]:
np.mean(abs(baseline_preds - test_labels))

5.0597701149425296

In [38]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
rf.

In [39]:
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
rf.fit(train_features, train_labels)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [42]:
predictions = rf.predict(test_features)
predictions

array([ 68.546,  60.784,  51.793,  60.927,  65.881,  70.528,  80.896,
        78.619,  62.719,  73.128,  63.602,  72.64 ,  38.65 ,  62.424,
        71.211,  56.204,  60.822,  56.842,  57.348,  76.862,  64.103,
        54.39 ,  65.619,  62.349,  58.085,  52.536,  67.117,  47.089,
        61.673,  78.307,  73.671,  64.337,  55.865,  80.073,  73.967,
        61.824,  53.672,  50.83 ,  68.275,  43.457,  70.446,  57.512,
        76.381,  42.691,  61.097,  73.52 ,  52.555,  79.094,  54.274,
        42.517,  46.701,  42.726,  64.663,  65.714,  74.633,  61.44 ,
        55.451,  59.685,  53.377,  59.33 ,  66.387,  50.397,  60.292,
        70.522,  59.998,  58.837,  71.516,  69.518,  75.912,  40.739,
        78.394,  56.005,  60.448,  49.752,  54.326,  63.445,  43.876,
        76.366,  48.199,  52.312,  53.308,  68.748,  73.033,  73.27 ,
        63.059,  58.692,  46.929])

In [43]:
errors = abs(predictions - test_labels)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 3.83 degrees.


In [46]:
mape = 100 * (errors / test_labels)
mape

array([  3.85757576,   0.35409836,   0.39807692,   7.68636364,
         5.88428571,  13.9902439 ,   4.82823529,   6.40595238,
         3.50923077,  20.51304348,   4.26557377,  14.54117647,
        12.15909091,   3.96307692,   3.20434783,   9.3483871 ,
         4.965625  ,   1.50357143,   8.20377358,   2.70632911,
         1.75079365,   4.57894737,   2.06119403,   0.56290323,
         1.55084746,   6.18571429,   3.25692308,   9.44423077,
         6.55606061,   3.03552632,  15.1109375 ,   5.4704918 ,
        16.38541667,   1.14444444,   3.93896104,   8.46315789,
         7.46206897,   8.14893617,   0.40441176,  14.79019608,
         8.51168831,   2.7       ,   4.63150685,  16.29215686,
         3.55423729,  15.49425287,   9.38793103,   2.35308642,
         6.42413793,   1.23095238,   4.69183673,   6.815     ,
         0.51846154,   2.678125  ,   6.61857143,   5.47692308,
         4.6245283 ,   4.71052632,   0.71132075,   1.11666667,
         0.91492537,   2.85102041,  13.75849057,   2.20

In [49]:
dir(rf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_estimator_type',
 '_get_param_names',
 '_make_estimator',
 '_set_oob_score',
 '_validate_X_predict',
 '_validate_estimator',
 '_validate_y_class_weight',
 'apply',
 'base_estimator',
 'base_estimator_',
 'bootstrap',
 'class_weight',
 'criterion',
 'decision_path',
 'estimator_params',
 'estimators_',
 'feature_importances_',
 'fit',
 'get_params',
 'max_depth',
 'max_features',
 'max_leaf_nodes',
 'min_impurity_decrease',
 'min_impurity_split',
 'min_sampl

In [54]:
from sklearn.tree import export_graphviz

In [68]:
tree2 = rf.estimators_[2]

In [69]:
export_graphviz(tree2)

/home/dongsu/anaconda3/lib/python3.5/site-packages/sklearn/tree/export.py:399: DeprecationWarning: out_file can be set to None starting from 0.18. This will be the default in 0.20.
  DeprecationWarning)


In [70]:
import pydot
(graph, ) = pydot.graph_from_dot_file('tree.dot')

In [71]:
graph.write_png('/home/dongsu/RFtree2.png')

In [72]:
rf.feature_importances_

array([ 0.        ,  0.01291001,  0.0250783 ,  0.02495857,  0.69220035,
        0.19731323,  0.02547392,  0.00486251,  0.00285047,  0.00433159,
        0.00290979,  0.00156225,  0.0028675 ,  0.0026815 ])

In [74]:
importances = list(rf.feature_importances_)
importances

[0.0,
 0.01291000702019327,
 0.025078298511596833,
 0.024958570238798029,
 0.69220035485697207,
 0.19731323227672856,
 0.025473922563595413,
 0.0048625094640276038,
 0.0028504676264593399,
 0.0043315922327292755,
 0.0029097947412191558,
 0.0015622506795637974,
 0.0028675008418274045,
 0.0026814989462885883]

In [76]:
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]

In [77]:
feature_importances

[('year', 0.0),
 ('month', 0.01),
 ('day', 0.029999999999999999),
 ('temp_2', 0.02),
 ('temp_1', 0.68999999999999995),
 ('average', 0.20000000000000001),
 ('friend', 0.029999999999999999),
 ('week_Fri', 0.0),
 ('week_Mon', 0.0),
 ('week_Sat', 0.0),
 ('week_Sun', 0.0),
 ('week_Thurs', 0.0),
 ('week_Tues', 0.0),
 ('week_Wed', 0.0)]

In [78]:
feature_importances = sorted(feature_importances, key = lambda x:x[1], reverse=True)
feature_importances

[('temp_1', 0.68999999999999995),
 ('average', 0.20000000000000001),
 ('day', 0.029999999999999999),
 ('friend', 0.029999999999999999),
 ('temp_2', 0.02),
 ('month', 0.01),
 ('year', 0.0),
 ('week_Fri', 0.0),
 ('week_Mon', 0.0),
 ('week_Sat', 0.0),
 ('week_Sun', 0.0),
 ('week_Thurs', 0.0),
 ('week_Tues', 0.0),
 ('week_Wed', 0.0)]

In [86]:
feature_importances

[('temp_1', 0.68999999999999995),
 ('average', 0.20000000000000001),
 ('day', 0.029999999999999999),
 ('friend', 0.029999999999999999),
 ('temp_2', 0.02),
 ('month', 0.01),
 ('year', 0.0),
 ('week_Fri', 0.0),
 ('week_Mon', 0.0),
 ('week_Sat', 0.0),
 ('week_Sun', 0.0),
 ('week_Thurs', 0.0),
 ('week_Tues', 0.0),
 ('week_Wed', 0.0)]

In [88]:
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances]

Variable: temp_1               Importance: 0.69
Variable: average              Importance: 0.2
Variable: day                  Importance: 0.03
Variable: friend               Importance: 0.03
Variable: temp_2               Importance: 0.02
Variable: month                Importance: 0.01
Variable: year                 Importance: 0.0
Variable: week_Fri             Importance: 0.0
Variable: week_Mon             Importance: 0.0
Variable: week_Sat             Importance: 0.0
Variable: week_Sun             Importance: 0.0
Variable: week_Thurs           Importance: 0.0
Variable: week_Tues            Importance: 0.0
Variable: week_Wed             Importance: 0.0


[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]